version: "3.8"

services:
  app:
    container_name: "app"
    restart: always
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo/teste
      - APP_SERVER_PORT=3000
      - NODE_ENV=developer
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    command: npm start:dev

  mongo:
    container_name: "mongo"
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null # --quiet